import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Financeiro, Contábil e Cadastros',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Financeiro',
          collapsed: true,
          items: [
            'financeiro/vfin0100',
            'financeiro/vfin0110',
            'financeiro/vfin0120',
            'financeiro/vfin0130',
            'financeiro/vfin0200',
            'financeiro/vfin0210',
            'financeiro/vfin0300',
            'financeiro/vfin0400',
            'financeiro/vfin0500',
            'financeiro/vfin0600',
            'financeiro/vfin0610',
            'financeiro/vfin0620',
          ],
        },
        {
          type: 'category',
          label: 'Contabilidade',
          collapsed: true,
          items: [
            'contabilidade/vctb0102',
            'contabilidade/vctb0200',
            'contabilidade/vctb0600',
            'contabilidade/vutl0555',
            'contabilidade/vutl0560',
          ],
        },
        {
          type: 'category',
          label: 'Cadastros & Plataforma',
          collapsed: true,
          items: [
            'cadastros/vemp0100',
            'cadastros/vfun0100',
            'cadastros/vloc0100',
            'cadastros/vcla0100',
            'cadastros/vcal0100',
            'cadastros/vpri0100',
            'cadastros/vsec0100',
            'cadastros/vusr0100',
            'cadastros/vadm0100',
            'cadastros/vaud0100',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Industrial e Produção',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Engenharia',
          collapsed: true,
          items: [
            'engenharia/vent0200',
            'engenharia/vent0210',
            'engenharia/vent0204',
            'engenharia/vent0202',
            'engenharia/vent0115',
            'engenharia/vent0363',
            'engenharia/vpme0102',
            'engenharia/vpme0102ite',
            'engenharia/vent0108',
            'engenharia/veng0204',
            'engenharia/vite0313',
            'engenharia/vite0114',
            'engenharia/vite0115',
            'engenharia/vite0116',
            'engenharia/vite0118',
            'engenharia/vite0129',
            'engenharia/vmaq0101',
            'engenharia/vmaq0300',
            'engenharia/veng0300',
            'engenharia/vbom0100',
            'engenharia/veng0400',
            'engenharia/vdes0100',
            'engenharia/veng0500',
            'engenharia/veng0600',
            'engenharia/veng0610',
            'engenharia/vcfg0100',
            'engenharia/vcfg0200',
            'engenharia/vcfg0300',
            'engenharia/vcfg0400',
            'engenharia/vcfg0500',
            'engenharia/vcfg0600',
          ],
        },
        {
          type: 'category',
          label: 'Planejamento',
          collapsed: true,
          items: [
            'planejamento/vpla0102',
            'planejamento/vpla0300',
            'planejamento/vpln0100',
            'planejamento/vmrp0200',
            'planejamento/vcal0200',
            'planejamento/vplc0200',
            'planejamento/vplc0211',
          ],
        },
        {
          type: 'category',
          label: 'Previsão de Vendas',
          collapsed: true,
          items: [
            'previsao/vpre0101',
            'previsao/vpre0102',
            'previsao/vpre0201',
            'previsao/vpre0251',
            'previsao/vpre0301',
          ],
        },
        {
          type: 'category',
          label: 'Manutenção',
          collapsed: true,
          items: [
            'manutencao/vman0202',
            'manutencao/vman0401',
            'manutencao/vaps0300',
          ],
        },
        {
          type: 'category',
          label: 'Suprimento',
          collapsed: true,
          items: [
            'suprimento/vavr0200',
            'suprimento/vcon0100',
            'suprimento/vcon0200',
            'suprimento/vcon0202',
            'suprimento/vcon0400',
            'suprimento/vpdc0200',
            'suprimento/vpdc0210',
            'suprimento/vvor0202',
            'suprimento/vpct0100',
            'suprimento/vtps0100',
            'suprimento/vter0100',
            'suprimento/vter0200',
            'suprimento/vter0300',
            'suprimento/vter0400',
          ],
        },
        {
          type: 'category',
          label: 'Importação',
          collapsed: true,
          items: [
            'importacao/vimp0101',
            'importacao/vimp0102',
            'importacao/vimp0200',
            'importacao/vimp0300',
          ],
        },
        {
          type: 'category',
          label: 'Inspeção',
          collapsed: true,
          items: [
            'inspecao/vins0106',
            'inspecao/vins0200',
            'inspecao/vins0201',
            'inspecao/vins0206',
            'inspecao/vins0313',
            'inspecao/vins0400',
            'inspecao/vavf0101',
            'inspecao/vavf0204',
            'inspecao/vavf0203',
            'inspecao/vavf0300',
            'inspecao/vsup0600',
          ],
        },
        {
          type: 'category',
          label: 'Assistência Técnica',
          collapsed: true,
          items: [
            'assistencia/vass0201',
            'assistencia/vass0402',
            'assistencia/vatc0280',
            'assistencia/vatc0380',
            'assistencia/vatc0480',
            'assistencia/vsac0200',
          ],
        },
        {
          type: 'category',
          label: 'Garantia',
          collapsed: true,
          items: ['garantia/vgar0211'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Comercial, Vendas e PDV',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Comercial',
          collapsed: true,
          items: [
            'comercial/vent0100',
            'comercial/vvnd0100',
            'comercial/vvnd0300',
            'comercial/vvnd0400',
            'comercial/vvnd0500',
            'comercial/vvnd0600',
            'comercial/vvnd0610',
            'comercial/vdpr0100',
            'comercial/vsac0100',
            'comercial/vcli0600',
            'comercial/vrep0600',
            'comercial/vexr0100',
          ],
        },
        {
          type: 'category',
          label: 'Cliente',
          collapsed: true,
          items: [
            'cliente/vcli0500',
            'cliente/vcli0510',
            'cliente/vcli0520',
            'cliente/vcli0530',
            'cliente/vcli0117',
            'cliente/vcli0202',
          ],
        },
        {
          type: 'category',
          label: 'PDV / Pedidos',
          collapsed: true,
          items: [
            'pdv/vpdv0108',
            'pdv/vpdv0111',
            'pdv/vpdv0200',
            'pdv/vpdv0253',
            'pdv/vvre0200',
            'pdv/vre0203',
          ],
        },
        {
          type: 'category',
          label: 'Almoxarifado',
          collapsed: true,
          items: [
            'almoxarifado/vent0800',
            'almoxarifado/vexp0100',
            'almoxarifado/vexp0110',
            'almoxarifado/vexp0120',
            'almoxarifado/vlot0100',
            'almoxarifado/vest0300',
            'almoxarifado/vest0400',
          ],
        },
        {
          type: 'category',
          label: 'Custos / Precificação',
          collapsed: true,
          items: ['custos/vcst0202'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Fiscal',
      collapsed: true,
      items: [
        'fiscal/vfis0100',
        'fiscal/vfis0110',
        'fiscal/vfis0120',
        'fiscal/vfis0200',
        'fiscal/vfis0210',
        'fiscal/vfis0220',
        'fiscal/vfis0300',
        'fiscal/vfis0310',
        'fiscal/vfis0320',
        'fiscal/vfis0330',
        'fiscal/vfis0340',
        'fiscal/vfis0350',
        'fiscal/vfis0360',
        'fiscal/vfis0500',
        'fiscal/vfis0510',
        'fiscal/vfis0520',
        'fiscal/vfis0530',
        'fiscal/vfis0540',
        'fiscal/vfis0550',
        'fiscal/vfis0560',
        'fiscal/vfis0600',
        'fiscal/vfis0610',
        'fiscal/vfis0620',
        'fiscal/vfis0630',
        'fiscal/vfis0640',
        'fiscal/vfis0660',
        'fiscal/vnfs0100',
      ],
    },
    {
      type: 'category',
      label: 'PCP, Chão de Fábrica, Estoque e Custos',
      collapsed: true,
      items: [
        'pcp/vitm0100',
        'pcp/vmrp0100',
        'pcp/vvnd0200',
        'pcp/vmaq0200',
        'pcp/vpro0100',
        'pcp/vpro0200',
        'pcp/vpro0210',
        'pcp/vpro0900',
        'pcp/vpro0300',
        'pcp/vpro0400',
        'pcp/vpro0500',
        'pcp/vpro0600',
        'pcp/vpro0700',
        'pcp/vpro0800',
        'pcp/vpro1000',
        'pcp/vpro1100',
        'pcp/vres0100',
        'pcp/vaps0100',
        'pcp/vaps0200',
        'pcp/vaps0400',
        'pcp/vaps0500',
        'pcp/vaps0600',
        'pcp/vcut0100',
        'pcp/vcus0100',
        'pcp/vest0100',
        'pcp/vest0200',
      ],
    },
    {
      type: 'category',
      label: 'Suprimento e Compras',
      collapsed: true,
      items: [
        'compras/vsup0500',
        'compras/vsup0510',
        'compras/vsup0110',
        'compras/vsup0120',
        'compras/vsup0130',
        'compras/vsup0200',
        'compras/vsup0300',
        'compras/vsup0400',
        'compras/vsup0610',
        'compras/vsup0620',
        'compras/vsup0630',
        'compras/vsup0640',
        'compras/vsup0650',
        'compras/vsup0660',
        'compras/vsup0670',
        'compras/vsup0680',
      ],
    },
  ],
};

export default sidebars;
