import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Financeiro, Contábil e Cadastros',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Financeiro',
          collapsed: true,
          items: [
            'financeiro/vfin0100',
            'financeiro/vfin0110',
            'financeiro/vfin0120',
            'financeiro/vfin0130',
            'financeiro/vfin0200',
            'financeiro/vfin0210',
            'financeiro/vfin0300',
            'financeiro/vfin0400',
            'financeiro/vfin0500',
          ],
        },
        {
          type: 'category',
          label: 'Contabilidade',
          collapsed: true,
          items: [
            'contabilidade/vctb0102',
            'contabilidade/vctb0200',
            'contabilidade/vutl0555',
          ],
        },
        {
          type: 'category',
          label: 'Cadastros',
          collapsed: true,
          items: [
            'cadastros/vemp0100',
            'cadastros/vfun0100',
            'cadastros/vloc0100',
            'cadastros/vcla0100',
            'cadastros/vcal0100',
            'cadastros/vpri0100',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Industrial e Produção',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Engenharia',
          collapsed: true,
          items: [
            'engenharia/vent0200',
            'engenharia/vent0210',
            'engenharia/vent0204',
            'engenharia/vent0202',
            'engenharia/vent0115',
            'engenharia/vent0363',
            'engenharia/vpme0102',
            'engenharia/vpme0102ite',
            'engenharia/vent0108',
            'engenharia/veng0204',
            'engenharia/vite0313',
            'engenharia/vite0114',
            'engenharia/vite0115',
            'engenharia/vite0116',
            'engenharia/vite0118',
            'engenharia/vite0129',
            'engenharia/vmaq0101',
          ],
        },
        {
          type: 'category',
          label: 'Planejamento',
          collapsed: true,
          items: [
            'planejamento/vpla0102',
            'planejamento/vplc0200',
            'planejamento/vplc0211',
          ],
        },
        {
          type: 'category',
          label: 'Previsão de Vendas',
          collapsed: true,
          items: [
            'previsao/vpre0101',
            'previsao/vpre0102',
            'previsao/vpre0201',
            'previsao/vpre0251',
            'previsao/vpre0301',
          ],
        },
        {
          type: 'category',
          label: 'Manutenção',
          collapsed: true,
          items: ['manutencao/vman0202', 'manutencao/vman0401'],
        },
        {
          type: 'category',
          label: 'Suprimento',
          collapsed: true,
          items: [
            'suprimento/vavr0200',
            'suprimento/vcon0100',
            'suprimento/vcon0200',
            'suprimento/vcon0202',
            'suprimento/vcon0400',
            'suprimento/vpdc0200',
            'suprimento/vvor0202',
          ],
        },
        {
          type: 'category',
          label: 'Importação',
          collapsed: true,
          items: [
            'importacao/vimp0101',
            'importacao/vimp0102',
            'importacao/vimp0200',
          ],
        },
        {
          type: 'category',
          label: 'Inspeção',
          collapsed: true,
          items: [
            'inspecao/vins0105',
            'inspecao/vins0106',
            'inspecao/vins0200',
            'inspecao/vins0201',
            'inspecao/vins0206',
            'inspecao/vins0211',
            'inspecao/vins0313',
            'inspecao/vins0400',
            'inspecao/vavf0101',
            'inspecao/vavf0105',
            'inspecao/vavf0204',
          ],
        },
        {
          type: 'category',
          label: 'Assistência Técnica',
          collapsed: true,
          items: [
            'assistencia/vass0201',
            'assistencia/vass0402',
            'assistencia/vatc0280',
            'assistencia/vatc0380',
            'assistencia/vatc0480',
          ],
        },
        {
          type: 'category',
          label: 'Garantia',
          collapsed: true,
          items: ['garantia/vgar0211'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Comercial, Vendas e PDV',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Comercial',
          collapsed: true,
          items: [
            'comercial/vent0100',
            'comercial/vvnd0100',
            'comercial/vexr0100',
          ],
        },
        {
          type: 'category',
          label: 'Cliente',
          collapsed: true,
          items: [
            'cliente/vcli0500',
            'cliente/vcli0510',
            'cliente/vcli0520',
            'cliente/vcli0530',
            'cliente/vcli0117',
            'cliente/vcli0202',
          ],
        },
        {
          type: 'category',
          label: 'PDV / Pedidos',
          collapsed: true,
          items: [
            'pdv/vpdv0108',
            'pdv/vpdv0111',
            'pdv/vpdv0200',
            'pdv/vpdv0253',
            'pdv/vvre0200',
            'pdv/vre0203',
          ],
        },
        {
          type: 'category',
          label: 'Almoxarifado',
          collapsed: true,
          items: ['almoxarifado/vent0800', 'almoxarifado/vexp0100'],
        },
        {
          type: 'category',
          label: 'Custos / Precificação',
          collapsed: true,
          items: ['custos/vcst0202'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Fiscal',
      collapsed: true,
      items: [
        'fiscal/vfis0100',
        'fiscal/vfis0110',
        'fiscal/vfis0200',
        'fiscal/vfis0210',
        'fiscal/vfis0220',
        'fiscal/vfis0300',
        'fiscal/vfis0310',
        'fiscal/vfis0320',
        'fiscal/vfis0330',
        'fiscal/vfis0340',
        'fiscal/vfis0350',
        'fiscal/vfis0360',
        'fiscal/vfis0500',
        'fiscal/vfis0510',
        'fiscal/vfis0520',
        'fiscal/vfis0530',
        'fiscal/vfis0540',
        'fiscal/vfis0550',
        'fiscal/vfis0560',
        'fiscal/vnfs0100',
      ],
    },
    {
      type: 'category',
      label: 'PCP, Chão de Fábrica, Estoque e Custos',
      collapsed: true,
      items: [
        'pcp/vitm0100',
        'pcp/vmrp0100',
        'pcp/vvnd0200',
        'pcp/vmaq0200',
        'pcp/vpro0100',
        'pcp/vpro0200',
        'pcp/vpro0210',
        'pcp/vpro0900',
        'pcp/vpro0300',
        'pcp/vpro0400',
        'pcp/vpro0500',
        'pcp/vpro0600',
        'pcp/vpro0700',
        'pcp/vpro0800',
        'pcp/vcut0100',
        'pcp/vcus0100',
        'pcp/vest0100',
        'pcp/vest0200',
      ],
    },
    {
      type: 'category',
      label: 'Suprimento e Compras',
      collapsed: true,
      items: [
        'compras/vsup0500',
        'compras/vsup0510',
        'compras/vsup0110',
        'compras/vsup0120',
        'compras/vsup0130',
        'compras/vsup0200',
        'compras/vsup0300',
        'compras/vsup0400',
      ],
    },
  ],
};

export default sidebars;
